### ISSUE TITLE
More languages

### ISSUE THREAD

**Issue by Minionguyjpro** [Wurst-Imperium/WI-Zoom#12]
Ive edited the mod and added some languages. Can it please be checked and added if good?
WI Zoom 1.17 jar with more languages:  [https://download1080.mediafire.com/3fuus8ldd1rg/dygtmhnhrgpzcfe/WI-Zoom-1.3-MC1.17.jar](url)

**Comment by RDKRACZ** [comment]
Can't you just make a pr or upload the text files? Btw the link is broken (I mean it points to nowhere but you can manually select it and then it works so it's something with Github markdown)
I think there is something broken with the archive since Gnome file-roller is unable to open it.

**Comment by Minionguyjpro** [comment]
What is gnome file roller?

**Comment by Minionguyjpro** [comment]
[Uploading de_de.txt…]()

**Comment by Minionguyjpro** [comment]
[pt_pt.txt](https://github.com/Wurst-Imperium/WI-Zoom/files/6680301/pt_pt.txt)
[ru_ru.txt](https://github.com/Wurst-Imperium/WI-Zoom/files/6680302/ru_ru.txt)

**Comment by Minionguyjpro** [comment]
[de_de.txt](https://github.com/Wurst-Imperium/WI-Zoom/files/6680303/de_de.txt)
[en_us.txt](https://github.com/Wurst-Imperium/WI-Zoom/files/6680304/en_us.txt)
[fr_fr.txt](https://github.com/Wurst-Imperium/WI-Zoom/files/6680305/fr_fr.txt)
[nl_nl.txt](https://github.com/Wurst-Imperium/WI-Zoom/files/6680306/nl_nl.txt)
[pt_pt.txt](https://github.com/Wurst-Imperium/WI-Zoom/files/6680307/pt_pt.txt)
[ru_ru.txt](https://github.com/Wurst-Imperium/WI-Zoom/files/6680308/ru_ru.txt)

**Comment by Minionguyjpro** [comment]
But if i start With Fabric it gives error.

**Comment by omerien** [comment]
What error ? Show us the logs. That's not helping saying "it doesn't work".

**Comment by Minionguyjpro** [comment]
Done. Pull request #33.
