### ISSUE TITLE
WI Zoom for Forge

### ISSUE THREAD

**Issue by Minionguyjpro** [Wurst-Imperium/WI-Zoom#13]
Make WI Zoom for Forge. I know theres no Forge 1.17 now, but if it is you can make it.

**Comment by RDKRACZ** [comment]
O-optifine?

**Comment by Alexander01998** [comment]
As of [WI Zoom 1.5](https://www.wimods.net/wi-zoom/wi-zoom-1-5/), I've added support for [NeoForge](https://neoforged.net/news/theproject/), which is a fork of Forge maintained by the original Forge team.
