### ISSUE TITLE
Versions not showing on CurseForge

### ISSUE THREAD

**Issue by chillytwastaken** [Wurst-Imperium/WI-Zoom#16]
For some reason I only see 1.18 and 1.18 snapshot versions on curseforge. Recently I wanted 1.17.1 but couldn't find it. (I have the link now), uh well yeah that's pretty much it.

**Comment by Alexander01998** [comment]
Works fine for me.

![image](https://user-images.githubusercontent.com/10100202/158243093-a044b0b4-c8ee-46c5-b852-d6a0e5d2638e.png)

**Comment by chillytwastaken** [comment]
Oh, I didn't realise the thing at the side, thanks!
