### ISSUE TITLE
wi zoom for forge 1.8.9 plzzzz

### ISSUE THREAD

**Issue by dolphin-cat** [Wurst-Imperium/WI-Zoom#17]
wi zoom for forge 1.8.9 plzzzz

**Comment by Alexander01998** [comment]
Hey dolphin-cat!

Thanks for reaching out, but I'm sorry to say that I currently don't have plans to support Forge 1.8.9. While I understand that there are still some players on older versions, it's just not feasible for me to support every version of Minecraft that's out there.

Thank you for your understanding.
