### ISSUE TITLE
1.19 mod load error - Fabric 1.19

### ISSUE THREAD

**Issue by FETXU** [Wurst-Imperium/WI-Zoom#22]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'WI Zoom' (wi_zoom) 1.4-MC1.19.1-rc1 with any version that is compatible with:
		 - minecraft 1.19
Unmet dependency listing:
	 - Mod 'WI Zoom' (wi_zoom) 1.4-MC1.19.1-rc1 requires any version between 1.19.1-alpha.22.24.a (inclusive) and 1.20- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.19!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

I am running Latest Fabric 1.19 build :(

**Comment by Alexander01998** [comment]
You are using a version of WI Zoom made for Minecraft 1.19.1-rc1, not 1.19.

Here is a list of WI Zoom releases that are made for Minecraft 1.19: https://www.curseforge.com/minecraft/mc-mods/wi-zoom/files/all?filter-status=1&filter-game-version=2020709689%3A9186

**Comment by Terrabytes13** [comment]
to piggyback off this issue, I seem to have issues of it not working at all even after i switch out the keybinds....
