### ISSUE TITLE
wi zoom not working in 1.19

### ISSUE THREAD

**Issue by ykking2811** [Wurst-Imperium/WI-Zoom#25]
![Screenshot 2022-08-26 205048](https://user-images.githubusercontent.com/84584667/186938611-1f832f9a-f4b5-4dbe-84d2-2a06cbd77d6a.png)
I am using wi zoom for a long time with almost the same mods and for some reason, it is not working for me on 1.19 it works on previous and later versions but not 1. 19

**Comment by omerien** [comment]
Same as #26 (stop using OptiFine and replace it by Sodium, Lithium and Phosphor for 1.15+)
