### ISSUE TITLE
Not working on 1.19 with optifine

### ISSUE THREAD

**Issue by lololouser** [Wurst-Imperium/WI-Zoom#26]
I have an issue with optifine, when i click zoom button nothing happening

**Comment by MrBreakNFix** [comment]
optifine has its own zoom. press "c"

**Comment by lololouser** [comment]
Yep, but I want 50x zoom

**Comment by neverlessy** [comment]
the same problem.

**Comment by MemesInTheTux** [comment]
same here, pressing V does nothing, changing the control to another key does nothing. I can only use the OptiFine zoom
