### ISSUE TITLE
23w05a Cannot change keybind

### ISSUE THREAD

**Issue by BaccarWozat** [Wurst-Imperium/WI-Zoom#34]
23w05a, Fabric 0.14.13, Fabric API 0.73.3, and WI-ZOOM 1.4.

Keybind is stuck at V and cannot be changed in the key binds menu, not even having a keybind option to change.

**Comment by Alexander01998** [comment]
Fabric Loader 0.14.14 and Fabric API 0.73.4+1.19.4 have fixed this bug.
