### ISSUE TITLE
Not working on 1.20.1

### ISSUE THREAD

**Issue by ItsukaHiro** [Wurst-Imperium/WI-Zoom#36]
Simple can't zoom when pressing key bind (any button)

**Comment by Alexander01998** [comment]
Hey @ItsukaHiro, thanks for bringing this issue to my attention. I've tested WI-Zoom on Minecraft version 1.20.1, and it seems to be working fine for me.

One possible reason for the zoom not working could be a keybind conflict with another mod or feature. Please double-check your keybinds to ensure there are no conflicts. Also, please confirm that WI Zoom is properly installed and that you can see the "WI Zoom" section in the key binds menu.

If the issue still persists, could you provide more details such as a list of any other mods or data/resource packs you have installed? This would help me to investigate further.
