### ISSUE TITLE
Mod URL is missing (Multi-mc)

### ISSUE THREAD

**Issue by 1oglop1** [Wurst-Imperium/WI-Zoom#4]
Thank you for amazing mod!

The URL provided in metadata seems to be missing

I tested this with Mod menu and URL there is correct however in MultiMC URL is missing

![image](https://user-images.githubusercontent.com/7480694/98094698-e8cc7b80-1e89-11eb-8911-2d49c06f22a6.png)

Other mods provide hyperlink which leads to the mod page

example:
![image](https://user-images.githubusercontent.com/7480694/98094827-19141a00-1e8a-11eb-809a-7506a5eaec6d.png)
`Tweakaroo` URL leads to the mod page

**Comment by Alexander01998** [comment]
Hmm. Tweakeroo seems to link their homepage in the same way as WI Zoom does:
- https://github.com/Wurst-Imperium/WI-Zoom/blob/master/src/main/resources/fabric.mod.json#L19
- https://github.com/maruohon/tweakeroo/blob/fabric_1.15.2/src/main/resources/fabric.mod.json#L12

Not sure why it would be displayed differently.

**Comment by 1oglop1** [comment]
Yeah I've checked other mods as well, sadly I know nothing about systems around to help with more debugging.
Maybe I could try to look at MultiMC, someone might know.

**Comment by Mrredstone5230** [comment]
It appears to have been fixed.

**Comment by Alexander01998** [comment]
Closing this issue as it seems to be resolved. Feel free to reopen if it isn't.
