### ISSUE TITLE
1.20 Zoom not working with Optifine 

### ISSUE THREAD

**Issue by SvalkerValentai** [Wurst-Imperium/WI-Zoom#40]
I use optifabric-1.13.25, and OptiFine_1.20_U_I5_pre5
mb this helps...

**Comment by omerien** [comment]
Stop using OptiFine
For 1.15 and after I recommand you Sodium, Lithium and Phosphor, they're Open Source and break way less things than OptiFine
OptiFabric isn’t even supported by OptiFine themselves
