### ISSUE TITLE
Neoforge 1.21(.1) Support

### ISSUE THREAD

**Issue by CassieRoseZA** [Wurst-Imperium/WI-Zoom#49]
Please can you add support for neoforge

**Comment by Alexander01998** [comment]
Hey @CassieRoseZA,

NeoForge is actually already supported for Minecraft 1.20.1. ([WI Mods](https://www.wimods.net/wi-zoom/wi-zoom-1-5/?mc=1.20.1), [Modrinth](https://modrinth.com/mod/wi-zoom/versions?l=neoforge), [CurseForge](https://www.curseforge.com/minecraft/mc-mods/wi-zoom/files/all?page=1&pageSize=20&gameVersionTypeId=6))

Maybe you mean NeoForge for Minecraft 1.21 specifically?

**Comment by Alexander01998** [comment]
Closing as NeoForge 1.21 and NeoForge 1.21.3 are now supported.  ([WI Mods](https://www.wimods.net/wi-zoom/wi-zoom-1-5/), [Modrinth](https://modrinth.com/mod/wi-zoom/versions?l=neoforge), [CurseForge](https://www.curseforge.com/minecraft/mc-mods/wi-zoom/files/all?page=1&pageSize=20&gameVersionTypeId=6))
