### ISSUE TITLE
21w10a Crash When Placing Sand

### ISSUE THREAD

**Issue by BaccarWozat** [Wurst-Imperium/WI-Zoom#7]
Placing lots and lots of falling sand really quickly causes a crash.
Removing WI Zoom fixes the problem.
Possibly a rendering issue (21w10a uses new rendering), but who knows?
[https://paste.ee/p/STWC2](https://paste.ee/p/STWC2) is the log. (Pardon all the Forge mods listed, they are disabled and not loaded by Fabric anyway.)

**Comment by Alexander01998** [comment]
This is a [known bug](https://github.com/FabricMC/fabric/issues/1360) in Fabric API version 0.32.1. It [has been fixed](https://github.com/FabricMC/fabric/pull/1364) yesterday. Please update to [Fabric API v0.32.2](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3236201).
