### ISSUE TITLE
Make zooming possible only when certain item is in the inventory.

### ISSUE THREAD

**Issue by RDKRACZ** [Wurst-Imperium/WI-Zoom#8]
Add optional check to make zooming work only when a configurable (enter ID) item is present in the inventory.
Firstly I wanted something like a spyglass but realized I can do the item by myself.

**Comment by Madis0** [comment]
> Add optional check to make zooming work only when a configurable (enter ID) item is present in the inventory.
> Firstly I wanted something like a spyglass but realized I can do the item by myself.

You are looking for this mod: https://www.curseforge.com/minecraft/mc-mods/quick-spyglasser

**Comment by RDKRACZ** [comment]
@Madis0 Before downvoting check the date of this issue... This was meant for 1.16 - no spyglass there.
